name: test
on: [pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      -
        name: Run tests
        run: make test
