name: test
on: [pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    container: golang:1.20
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run tests
        run: make test
